networks:
  yii:
    name: yii

services:
  nginx:
    container_name: yii_nginx
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./voteSystem:/var/voteSystem
      - ./vhost.conf:/etc/nginx/conf.d/default.conf
    networks:
      - yii
    depends_on:
      - php
  php:
    container_name: yii_php
    build: ./images/php74fpm
    volumes:
      - ./voteSystem:/var/voteSystem
      - ./php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - yii
    depends_on:
      - postgres
  postgres:
    container_name: yii_postgres
    image: postgres:latest
    volumes:
      - ./voteSystem:/var/voteSystem
      - ./postgresql-data:/var/lib/postgresql
      - ./postgres.cnf:/etc/postgres/conf.d/postgres.cnf
    environment:
      - POSTGRES_USER=vote_system
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=vote_system
    networks:
      - yii
